# Generated by Django 5.2.8 on 2025-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
